name: food_map
version: 0.0.1
author: Jens Loven-Holt <jlovenholt@gmail.com>
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular: "1.1.2"
  browser: "0.10.0+2"
  dart_to_js_script_rewriter: "0.1.0+1"
  google_maps: "3.0.2"
  route_hierarchical: "0.6.2"
transformers:
- dart_to_js_script_rewriter
- angular
